[package]
name = "mortgage-calculator-test-suite"
version = "0.1.0"
edition = "2024"

[dependencies]
cucumber = "0.21.1"
tokio = { version = "1.45.0", features = ["macros", "rt-multi-thread"] }

[[test]]
name = "main"
harness = false
